spring:
  application:
    name: "spring boot 3 mq use case"
  devtools:
    livereload:
      enabled: true
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:5039
    consumer:
      group-id: myGroup
  datasource:
    url: jdbc:postgresql://localhost:5432/DB_MQ_USE_CASE
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
